FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /guild_manager_discord ./cmd/discord

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /guild_manager_discord /guild_manager_discord
ENTRYPOINT ["/guild_manager_discord"]
